### ISSUE TITLE
Setup with `helmfile init --force` by default

### ISSUE THREAD

**Issue by lucasfcnunes** [helmfile/helmfile-action#179]
Helmfile has a default way to setup everything it uses by using `helmfile init --force`. It installs Helm, helm-diff, helm-secrets, helm-s3, helm-git with their helmfile recommended versions [check here](https://github.com/xiaomudk/helmfile/blob/490bb5d1474fa3a79bcffabf2d8984a77e3862cc/pkg/app/init.go#L19-L57).

Currently to setup those default helmfile (basic) plugins we need to specify them as follows (maybe breaking tested compatibility):
```yaml
- uses: helmfile/helmfile-action@v1.0.0
  with:
    helmfile-version: 'v0.150.0'
    helm-version: 'v3.11.0'
    helm-plugins: >
      https://github.com/databus23/helm-diff,
      https://github.com/jkroepke/helm-secrets
    helmfile-args: apply --environment prod
```

PS: I'm not pushing for the removal of `helm-plugins:` or `helm-version:` optioons.

First introduction of `helmfile init`: https://github.com/helmfile/helmfile/pull/389
