### ISSUE TITLE
All outputs are empty?

### ISSUE THREAD

**Issue by ben851** [helmfile/helmfile-action#218]
I'm trying to take the stdout of helmfile diff and and post it as a comment in the PR. Every output seems to be empty (I've tried helmfile-stdout, helmfile-stderr and exit-code). Am I missing something? I've verified that writing static text in the pr comment action works as expected, and I can get outputs from other actions and add them as a comment. 

``` yaml
    - name: Run helmfile
       id: helmfile_diff
       uses: helmfile/helmfile-action@v1.0.0
       with:
         helmfile-args: diff --environment staging
    - name: Helmfile Diff Comment
      uses: mshick/add-pr-comment@v2
      with:
        message: | 
          ${{ steps.helmfile_diff.outputs.helmfile-stdout }}
```
