### ISSUE TITLE
How can I supply my kubeconfig file?

### ISSUE THREAD

**Issue by wjentner** [helmfile/helmfile-action#281]
I've tried to add it as an env variable (KUBECONFIG & KUBECONFIG_FILE) from github secrets but no success.

My current workaround is:

```
    - name: WriteKubeConfig
      run: |
        mkdir -p ~/.kube
        echo "$KUBECONFIG_CONTENT" > ~/.kube/config
      env:
        KUBECONFIG_CONTENT: '${{ secrets.KUBECONFIG }}'

    - uses: helmfile/helmfile-action@v1.9.1
      with:
        helm-plugins: >
          https://github.com/databus23/helm-diff,
          https://github.com/jkroepke/helm-secrets
        helmfile-args: apply
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}
```

But perhaps there is an easier way?
