### ISSUE TITLE
Colourised output in GH actions?

### ISSUE THREAD

**Issue by jess-belliveau** [helmfile/helmfile-action#362]
When I run `helmfile diff` locally, my output is coloured by default:
![image](https://github.com/user-attachments/assets/42123fcd-24ac-40b9-9cf0-847a71640c8b)

The same diff when represented in the output from this action is not coloured - is there an arg/param we are missing?

```
      - name: Run helmfile diff
        uses: helmfile/helmfile-action@v1.9.1
        with:
          helmfile-version: 'v0.163.1'
          helm-version: 'v3.14.3'
          helmfile-workdirectory: "./helm"
          helm-plugins: >
            https://github.com/databus23/helm-diff, https://github.com/jkroepke/helm-secrets, https://github.com/hypnoglow/helm-s3, https://github.com/aslafy-z/helm-git
          helmfile-args: diff
          helmfile-auto-init: "false"
```

![image](https://github.com/user-attachments/assets/fd2e2b28-92d4-460b-b3ad-02fbb720444f)
