### ISSUE TITLE
`Error: Parameter token or opts.auth is required`

### ISSUE THREAD

**Issue by joshfrench** [helmfile/helmfile-action#37]
I'm getting this error and I can't figure out why, since there's no mention of `token` or `opts.auth` in the source code. Here's a [sample workflow](https://github.com/joshfrench/helmfile-action/actions/runs/5061461558/workflow):
```yaml
name: test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install helmfile
        uses: helmfile/helmfile-action@v1.0.0
```

And the [output](https://github.com/joshfrench/helmfile-action/actions/runs/5061461558/jobs/9085714179):
```
Run helmfile/helmfile-action@v1.0.0
  with:
    helmfile-version: latest
    helm-version: latest
    helm-plugins: https://github.com/databus/helm-diff
Error: Parameter token or opts.auth is required
```

Any ideas? Thanks!
